#!/bin/sh
source /boot/config/plugins/openvpnserver-tun/openvpnserver_cert.cfg

if [ "$INSTALL_ON_BOOT" = "enable" ]; then	
	 # Start OpenVPN server
	logger "Starting OpenVPN Server"
	/usr/local/emhttp/plugins/openvpnserver-tun/scripts/rc.openvpnserver start | logger
fi
