#!/bin/bash
source /boot/config/plugins/openvpnserver-tun/openvpnserver_cert.cfg
if [[ "$DISCONNECT_ON_UMOUNT" == "yes" ]]; then
	logger "Stopping OpenVPN Server"
	/usr/local/emhttp/plugins/openvpnserver-tun/scripts/rc.openvpnserver stop | logger
fi